HOTEL/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'HOTEL'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('menu', views.menu, name='menu'),
    path('gallery', views.gallery, name='gallery'),
    path('contact', views.contact, name='contact'),
    path('search_room', views.search_rooms, name='search-room'),
    path('reserve_room/<int:room_number>/', views.reserve_room, name='reserve-room'),
    path('booking_successful/<int:reservation_id>/', views.success, name='success'),

    # May
    path('payment/', views.payment, name='payment'),
    # path('success', views.payment_success, name='payment-success'),
    path('success' , views.success , name='success'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('room_canceled/<int:reservation_id>/', views.room_canceled, name='cancel-reservation'),
    path('cancel_success', views.cancel_success, name='cancel-success'),
    path('add_room', views.add_room, name='add-room'),
    path('contact_view', views.contact_view, name='contact'),
    
    # Table Reservation
    path('table_reservation', views.table_reservation, name='table-reservation'),
    path('reservation_confirmation', views.table_confirm, name='reservation-confirmation'),
    path('table_cancel/<int:tablereservation_id>', views.cancel_table, name='table-cancel'),

    # Authentications
    path('accounts/login/', auth_views.LoginView.as_view(template_name='authentication/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('accounts/profile/', views.profile, name='profile')
]

HotelChawngthu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HOTEL.urls')),
]

HOTEL/models.py
from django.db import models
from django.contrib.auth.models import User

class Room(models.Model):
    room_number = models.CharField(max_length=10)
    room_type = models.CharField(max_length=100)
    room_description = models.TextField(max_length=300)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    is_booked = models.BooleanField(default=False)
    image = models.ImageField(upload_to='static/room_images/')

    def __str__(self):
        return self.room_number


class Guest(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Reservation(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    guest = models.ForeignKey(Guest, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.guest}'s reservation for Room {self.room.room_number}"



class TableReservation(models.Model):
    TABLE_NUMBER_CHOICES = (
        ('1', 'Table 1'),
        ('2', 'Table 2'),
        ('3', 'Table 3'),
        ('4', 'Table 4'),
        ('5', 'Table 5'),
        ('6', 'Table 6'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=50)
    reserve_date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    guest = models.IntegerField()
    table_number = models.CharField(max_length=2, choices=TABLE_NUMBER_CHOICES)

    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.reserve_date}"


    

HOTEL/forms.py
from django import forms
from django.core.mail import send_mail

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        send_mail(
            f"New message from {name} ({email})",
            message,
            email,
            ['fakeavangchhia@gmail.com'],
            fail_silently=False,
        )

HOTEL/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.views.decorators.csrf import csrf_exempt
from django.utils.translation import gettext_lazy as _
from .models import Room, Reservation, Guest, TableReservation
import razorpay
from django.conf import settings
from django.shortcuts import get_object_or_404


from django.contrib import messages
from .models import TableReservation

# Contact
from .forms import ContactForm

# auth
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout


def index(request):
    return render(request, 'hotel/index.html', {})


def about(request):
    return render(request, 'hotel/about.html', {})


def menu(request):
    return render(request, 'hotel/menu.html', {})


def contact(request):
    return render(request, 'hotel/contact.html', {})


def gallery(request):
    return render(request, 'hotel/gallery.html', {})


@login_required
def search_rooms(request):
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')
    available_rooms = Room.objects.filter(is_booked=False)
    if start_date and end_date:
        # Find reservations that overlap with the requested dates
        reservations = Reservation.objects.filter(
            Q(start_date__range=[start_date, end_date]) | Q(end_date__range=[start_date, end_date])
        )
        booked_rooms = [reservation.room for reservation in reservations]
        available_rooms = available_rooms.exclude(pk__in=[room.pk for room in booked_rooms])
    context = {'available_rooms_list': available_rooms, 'start_date': start_date, 'end_date': end_date}
    return render(request, 'booking/room_search.html', context)



@login_required
def add_room(request):
    if request.method == 'POST':
        room = Room(
            room_number=request.POST.get('room_number'),
            room_type=request.POST.get('room_type'),
            room_description=request.POST.get('room_description'),
            price=request.POST.get('price'),
            is_booked=request.POST.get('is_booked'),
            image=request.FILES.get('image')
        )
        room.save()
        context = {
            'room_number': room.room_number
        }
        return render(request, 'booking/room_added.html', context)
    else:
        return render(request, 'booking/add_room.html')



# function for the reserve room and making payment.
@csrf_exempt
@login_required
def reserve_room(request, **kwargs):
    room_number = kwargs['room_number']
    room = Room.objects.get(room_number=room_number)
    price = room.price
    user = request.user

    if request.method == 'POST':
        # Check if a guest object already exists for the user
        guest, created = Guest.objects.get_or_create(user=user)

        # Update the fields of the existing guest object using the form data
        guest.first_name = request.POST['first_name']
        guest.last_name = request.POST['last_name']
        guest.email = request.POST['email']
        guest.phone_number = request.POST['phone_number']
        guest.save()

        # Create a new Reservation object using the form data and the Guest object
        reservation = Reservation.objects.create(
            room=Room.objects.get(room_number=request.POST['room_number']),
            start_date=request.POST['start_date'],
            end_date=request.POST['end_date'],
            guest=guest
        )
        # Render the reservation_confirm template after payment successful
        return render(request, 'booking/success.html', {'reservation': reservation})
    else:
        # Render the form for the user to fill out
        return render(request, 'booking/reserve_room.html', {
            'room_number': room_number,
            'price': price * 100,
        })



@csrf_exempt
def booking_success(request, reservation_id):
    reservation = Reservation.objects.get(id=reservation_id)
    print(reservation)
    context = {'reservation': reservation}
    return render(request, 'booking/success.html', context)



def room_canceled(request, reservation_id):
    reservation = get_object_or_404(Reservation, id=reservation_id)
    reservation.delete()
    return redirect('HOTEL:cancel-success')




def cancel_success(request):
    return render(request, 'booking/room_canceled.html')   


def payment(request):
    if request.method == "POST":
        name = request.POST.get('name')
        amount = 50000

        client = razorpay.Client(
            auth=("rzp_test_N94crIsOHAqIqA", "mO0T0vP3J6wajyEV6UDDztoG"))

        payment = client.order.create({'amount': amount, 'currency': 'INR',
                                       'payment_capture': '1'})
    return render(request, 'booking/payment.html')

@csrf_exempt
def success(request):
    return render(request, "booking/success.html")


@csrf_exempt
def success(request, reservation_id):
    reservation = Reservation.objects.all(id=reservation_id)
    context = {'reservation': reservation}
    return render(request, 'booking/success.html', context)


@login_required
def dashboard(request):
    user = request.user
    
    if user.is_staff:
        # User is a manager - show all reservations
        reservations = Reservation.objects.all()
        tables = TableReservation.objects.all
        guests = Guest.objects.all()
    else:
        # User is a guest - show only their own reservations
        reservations = Reservation.objects.filter(guest__user=user)
        tables = TableReservation.objects.filter(user=user)
        guests = Guest.objects.filter(reservation__guest__user=request.user)

    
    return render(request, 'booking/dashboard.html', {
        'user': user,
        'reservations': reservations,
        'tables': tables, 
        'guests': guests
        })



# authentications
@csrf_exempt
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('HOTEL:profile')
    else:
        form = UserCreationForm()
    return render(request, 'authentication/signup.html', {
        'form': form
    })


def custom_logout(request):
    logout(request)
    return redirect('HOTEL:index')

@login_required
def profile(request):
    user = request.user
    context = {
        'user': user
    }
    return render(request, 'authentication/profile.html', context)



@login_required
def table_reservation(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        reserve_date = request.POST['reserve_date']
        start_time = request.POST['start_time']
        end_time = request.POST['end_time']
        guest = request.POST['guest']
        table_number = request.POST['table_number']

        # Check if table is available for reservation
        reservations = TableReservation.objects.filter(
            table_number=table_number,
            reserve_date=reserve_date,
            start_time__lte=end_time,
            end_time__gte=start_time,
        )

        if reservations.exists():
            messages.error(request, 'This table is not available for the selected date and time. Please choose another table or time.')
            return redirect('HOTEL:table-reservation')

        # Create a new reservation
        user = request.user
        reservation = TableReservation(
            user=user,
            first_name=first_name,
            last_name=last_name,
            reserve_date=reserve_date,
            start_time=start_time,
            guest=guest,
            end_time=end_time,

            table_number=table_number,
        )
        reservation.save()
        return redirect('HOTEL:reservation-confirmation')

    else:
        tables = TableReservation.TABLE_NUMBER_CHOICES
        context = {
            'table_choices': tables
        }
        return render(request, 'table/reservation.html', context)


    
def table_confirm(request):
    table = TableReservation.objects.filter(user=request.user).latest('id')
    
    table_number = table.table_number
    time = table.start_time
    return render(request, 'table/reservation_confimation.html', {
        'table_number': table_number,
        'time': time
    })

def cancel_table(request, tablereservation_id):
    table = get_object_or_404(TableReservation, id=tablereservation_id)
    table.delete()
    return redirect('HOTEL:cancel-success')


# contact page
@login_required
def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.send_email()
            return render(request, 'authentication/email_sent.html')
    else:
        form = ContactForm()

    context = {
        'form': form,
        'recipient_email': 'fakeavangchhia@.com', # replace with your email address
    }
    return render(request, 'hotel/contact.html', context)

HOTEL/templates/hotel/about.html
{% extends 'hotel/base.html' %}

{% load static %}
{% block content %}
	{% block title %}About{% endblock %}

	<!-- Start header -->
	<div class="all-page-title page-breadcrumb">
		<div class="container text-center">
			<div class="row">
				<div class="col-lg-12">
					<h1>About Us</h1>
				</div>
			</div>
		</div>
	</div>
	<!-- End header -->
	
	<!-- Start About -->
	<div class="about-section-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-6">
					<img src="{% static 'HotelChawngthu/images/story.jpeg' %}" alt="" class="img-fluid">
				</div>
				<div class="col-lg-6 col-md-6 text-center">
					<div class="inner-column">
						<h1>Welcome To <span>Team - 3 Project</span></h1>
						<h4>Little Story</h4>
						<p>He kan project hi complete website chu a la ni chiah lo nain mahse BCA Major atan chuan a tha thawkhatin kan hria ani. Kan project ah hian python library pakhat django framework kan hmanga, he framework hi minor project siam nana kan hman tho kha ani a, a powerful piah lamah a awlsam em em bawk ani. </p>
						<p>Kan project kan thlan dawn hian awm hmun survey kan nei nasa hle a, enge mipui te hian an mamawh ang tih te, mahse college thil anih vangin mipui ai mah chuan kan tana chaw free dawn theihna tur awm ang kha kan ngaihtuah a, Hotel Chawngthu hi kan thlang ta ani.</p>
						<a class="btn btn-lg btn-circle btn-outline-new-white" href="{% url 'HOTEL:table-reservation' %}">Reservation</a>
					</div>
				</div>
				<div class="col-md-12">
					<div class="inner-pt">
						<p>Kan major project hi duh ang takin kan peih hman lo nain vawiin a kan rawn present thei hi kan in chhuang hle a, kan hriat angin python hi college ah kan zir lova, mahse he kan project hi Mizoram ah Hackathon rawn nei leh pawh nise, publis ve ka ngam ang.</p>
						<p>Major project kan han khawih chiah hian kan project a kan hlawkna ber pakhat chu BCA major project hi software siam ringawt ni lovin Business lama hma min sawn tir tu ani a, Client te nena in dawr dan te, design pawimawhna hran hrang te, mimal chauha tih chi ni lovin team work anih zia te kan hre thar bawk ani.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End About -->
	
	

{% endblock %}

HOTEL/templates/hotel/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en"><!-- Basic -->
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">   
   
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
 
     <!-- Site Metas -->
    <title>{% block title %} HOTEL CHAWNGTHU {% endblock %} </title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="{% static 'HotelChawngthu/images/favicon.ico' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'HotelChawngthu/images/apple-touch-icon.png' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'HotelChawngthu/css/bootstrap.min.css' %}">
	<!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'HotelChawngthu/css/style.css' %}">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'HotelChawngthu/css/responsive.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'HotelChawngthu/css/custom.css' %}">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Room display animation -->
    <!-- Include Animate.css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">

    <!-- Include jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


</head>

<body>
	<!-- Start header -->
	<header class="top-navbar">
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<div class="container">
				<a class="navbar-brand" href="{% url 'HOTEL:index' %}">
					<img src="{% static 'HotelChawngthu/images/chawgthu.png' %}" alt="" />
				</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars-rs-food" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
				  <span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbars-rs-food">
					<ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'HOTEL:index' %}">Home</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'HOTEL:menu' %}">Menu</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'HOTEL:about' %}">About</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'HOTEL:dashboard' %}">Dashboard</a></li>
                            {% if user.is_staff %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'HOTEL:add-room' %}">Add room</a></li>
                            {% endif %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="dropdown-a" data-toggle="dropdown">Reservation</a>
                                <div class="dropdown-menu" aria-labelledby="dropdown-a">
                                    <a class="dropdown-item" href="{% url 'HOTEL:table-reservation' %}">Table</a>
                                    <a class="dropdown-item" href="{% url 'HOTEL:search-room' %}">Room</a>
                                </div>
                            </li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'HOTEL:contact' %}">Contact</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'HOTEL:gallery' %}">Gallery</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'HOTEL:logout' %}">Logout</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'HOTEL:index' %}">Home</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'HOTEL:menu' %}">Menu</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'HOTEL:about' %}">About</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'HOTEL:gallery' %}">Gallery</a></li>
						    <li class="nav-item"><a class="nav-link" href="{% url 'HOTEL:login' %}">Login</a></li>
						    <li class="nav-item"><a class="nav-link" href="{% url 'HOTEL:signup' %}">Signup</a></li>
                        {% endif %}
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<!-- End header -->

{% block content %}

{% endblock %}

<!-- Start Contact info -->
<div class="contact-imfo-box">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <i class="fa fa-volume-control-phone"></i>
                <div class="overflow-hidden">
                    <h4>Phone</h4>
                    <p class="lead">
                        +91 98625 26788
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                <i class="fa fa-envelope"></i>
                <div class="overflow-hidden">
                    <h4>Email</h4>
                    <p class="lead">
                        hotelchawngthu@gmail.com
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                <i class="fa fa-map-marker"></i>
                <div class="overflow-hidden">
                    <h4>Location</h4>
                    <p class="lead">
                        Vengthlang, Champhai
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Contact info -->

<!-- Start Footer -->
<footer class="footer-area bg-f">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <h3>About Us</h3>
                <p>The food provided here is fresh and obtained from farmers and gardeners around the area and the prices are pocket friendly too even for those who earn their daily livelihood.</p>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3>Opening hours</h3>
                <p><span class="text-color">Monday: </span>Closed</p>
                <p><span class="text-color">Tue-Wed :</span> 9:Am - 10PM</p>
                <p><span class="text-color">Thu-Fri :</span> 9:Am - 10PM</p>
                <p><span class="text-color">Sat-Sun :</span> 5:PM - 10PM</p>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3>Contact information</h3>
                <p class="lead">Vengthlang north, Champhai</p>
                <p class="lead"><a href="tel: 91 9362630203">+91 87982 45559</a></p>
                <p><a href="#"> hotel@chawngthu.com</a></p>
            </div>
            <div class="col-lg-3 col-md-6">
                <ul class="list-inline f-social">
                    <li class="list-inline-item"><a href="https://www.facebook.com/HotelChawngthu?mibextid=LQQJ4d"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                    <li class="list-inline-item"><a href="https://instagram.com/hotelchawngthu?igshid=ZWQyN2ExYTkwZQ=="><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
    
    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p class="company-name">All Rights Reserved. &copy; 2023 <a href="{% url 'HOTEL:index' %}">Major Project</a> Design By : 
                Team - 3</p>
                </div>
            </div>
        </div>
    </div>
    
</footer>
<!-- End Footer -->



<a href="#" id="back-to-top" title="Back to top" style="display: none;">&uarr;</a>

<!-- ALL JS FILES -->
<script src="{% static 'HotelChawngthu/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'HotelChawngthu/js/popper.min.js' %}"></script>
<script src="{% static 'HotelChawngthu/js/bootstrap.min.js' %}"></script>
<!-- ALL PLUGINS -->
<script src="{% static 'HotelChawngthu/js/jquery.superslides.min.js' %}"></script>
<script src="{% static 'HotelChawngthu/js/images-loded.min.js' %}"></script>
<script src="{% static 'HotelChawngthu/js/isotope.min.js' %}"></script>
<script src="{% static 'HotelChawngthu/js/baguetteBox.min.js' %}"></script>
<script src="{% static 'HotelChawngthu/js/form-validator.min.js' %}"></script>
<script src="{% static 'HotelChawngthu/js/contact-form-script.js' %}"></script>
<script src="{% static 'HotelChawngthu/js/custom.js' %}"></script>
</body>
</html>

HOTEL/templates/hotel/contact.html
{% extends 'hotel/base.html' %}

{% block content %}
<br><br><br><br>
<div class="all-page-title page-breadcrumb">
  <div class="container text-center">
    <div class="row">
      <div class="col-lg-12">
        <h1>Find Us on the map.</h1>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3659.507774109033!2d93.3226206745544!3d23.47821329917279!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x374c5b4fbafdea93%3A0xae798061f7f6291e!2sHotel%20Chawngthu!5e0!3m2!1sen!2sin!4v1683730040625!5m2!1sen!2sin" width="1000" height="400" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
      </div>
    </div>
  </div>
</div>
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <h1 class="text-center mb-5">Contact Us</h1>
        <form method="post" action="">
          {% csrf_token %}
          <div class="form-group">
            <label for="{{ form.name.id_for_label }}">Name</label>
            <input type="text" class="form-control" id="{{ form.name.id_for_label }}" name="{{ form.name.name }}" placeholder="Enter your name" required>
          </div>
          <div class="form-group">
            <label for="{{ form.email.id_for_label }}">Email</label>
            <input type="email" class="form-control" id="{{ form.email.id_for_label }}" name="{{ form.email.name }}" placeholder="Enter your email" required>
          </div>
          <div class="form-group">
            <label for="{{ form.message.id_for_label }}">Message</label>
            <textarea class="form-control" id="{{ form.message.id_for_label }}" name="{{ form.message.name }}" rows="5" placeholder="Enter your message" required></textarea>
          </div>
          <button type="submit" class="border border-warning btn btn-outline-warning">Send Message</button>
        </form>
      </div>
    </div>
  </div>
<br>
{% endblock %}