HOTEL/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'HOTEL'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('menu', views.menu, name='menu'),
    path('gallery', views.gallery, name='gallery'),
    path('contact', views.contact, name='contact'),
    path('search_room', views.search_rooms, name='search-room'),
    path('reserve_room/<int:room_number>/', views.reserve_room, name='reserve-room'),
    path('booking_successful/<int:reservation_id>/', views.success, name='success'),

    # May
    path('payment/', views.payment, name='payment'),
    # path('success', views.payment_success, name='payment-success'),
    path('success' , views.success , name='success'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('room_canceled/<int:reservation_id>/', views.room_canceled, name='cancel-reservation'),
    path('cancel_success', views.cancel_success, name='cancel-success'),
    path('add_room', views.add_room, name='add-room'),
    path('contact_view', views.contact_view, name='contact'),
    
    # Table Reservation
    path('table_reservation', views.table_reservation, name='table-reservation'),
    path('reservation_confirmation', views.table_confirm, name='reservation-confirmation'),
    path('table_cancel/<int:tablereservation_id>', views.cancel_table, name='table-cancel'),

    # Authentications
    path('accounts/login/', auth_views.LoginView.as_view(template_name='authentication/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('accounts/profile/', views.profile, name='profile')
]

HotelChawngthu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HOTEL.urls')),
]

HOTEL/models.py
from django.db import models
from django.contrib.auth.models import User

class Room(models.Model):
    room_number = models.CharField(max_length=10)
    room_type = models.CharField(max_length=100)
    room_description = models.TextField(max_length=300)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    is_booked = models.BooleanField(default=False)
    image = models.ImageField(upload_to='static/room_images/')

    def __str__(self):
        return self.room_number


class Guest(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Reservation(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    guest = models.ForeignKey(Guest, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.guest}'s reservation for Room {self.room.room_number}"



class TableReservation(models.Model):
    TABLE_NUMBER_CHOICES = (
        ('1', 'Table 1'),
        ('2', 'Table 2'),
        ('3', 'Table 3'),
        ('4', 'Table 4'),
        ('5', 'Table 5'),
        ('6', 'Table 6'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=50)
    reserve_date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    guest = models.IntegerField()
    table_number = models.CharField(max_length=2, choices=TABLE_NUMBER_CHOICES)

    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.reserve_date}"


    

HOTEL/forms.py
from django import forms
from django.core.mail import send_mail

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        send_mail(
            f"New message from {name} ({email})",
            message,
            email,
            ['fakeavangchhia@gmail.com'],
            fail_silently=False,
        )

HOTEL/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.views.decorators.csrf import csrf_exempt
from django.utils.translation import gettext_lazy as _
from .models import Room, Reservation, Guest, TableReservation
import razorpay
from django.conf import settings
from django.shortcuts import get_object_or_404


from django.contrib import messages
from .models import TableReservation

# Contact
from .forms import ContactForm

# auth
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout


def index(request):
    return render(request, 'hotel/index.html', {})


def about(request):
    return render(request, 'hotel/about.html', {})


def menu(request):
    return render(request, 'hotel/menu.html', {})


def contact(request):
    return render(request, 'hotel/contact.html', {})


def gallery(request):
    return render(request, 'hotel/gallery.html', {})


@login_required
def search_rooms(request):
    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')
    available_rooms = Room.objects.filter(is_booked=False)
    if start_date and end_date:
        # Find reservations that overlap with the requested dates
        reservations = Reservation.objects.filter(
            Q(start_date__range=[start_date, end_date]) | Q(end_date__range=[start_date, end_date])
        )
        booked_rooms = [reservation.room for reservation in reservations]
        available_rooms = available_rooms.exclude(pk__in=[room.pk for room in booked_rooms])
    context = {'available_rooms_list': available_rooms, 'start_date': start_date, 'end_date': end_date}
    return render(request, 'booking/room_search.html', context)



@login_required
def add_room(request):
    if request.method == 'POST':
        room = Room(
            room_number=request.POST.get('room_number'),
            room_type=request.POST.get('room_type'),
            room_description=request.POST.get('room_description'),
            price=request.POST.get('price'),
            is_booked=request.POST.get('is_booked'),
            image=request.FILES.get('image')
        )
        room.save()
        context = {
            'room_number': room.room_number
        }
        return render(request, 'booking/room_added.html', context)
    else:
        return render(request, 'booking/add_room.html')



# function for the reserve room and making payment.
@csrf_exempt
@login_required
def reserve_room(request, **kwargs):
    room_number = kwargs['room_number']
    room = Room.objects.get(room_number=room_number)
    price = room.price
    user = request.user

    if request.method == 'POST':
        # Check if a guest object already exists for the user
        guest, created = Guest.objects.get_or_create(user=user)

        # Update the fields of the existing guest object using the form data
        guest.first_name = request.POST['first_name']
        guest.last_name = request.POST['last_name']
        guest.email = request.POST['email']
        guest.phone_number = request.POST['phone_number']
        guest.save()

        # Create a new Reservation object using the form data and the Guest object
        reservation = Reservation.objects.create(
            room=Room.objects.get(room_number=request.POST['room_number']),
            start_date=request.POST['start_date'],
            end_date=request.POST['end_date'],
            guest=guest
        )
        # Render the reservation_confirm template after payment successful
        return render(request, 'booking/success.html', {'reservation': reservation})
    else:
        # Render the form for the user to fill out
        return render(request, 'booking/reserve_room.html', {
            'room_number': room_number,
            'price': price * 100,
        })



@csrf_exempt
def booking_success(request, reservation_id):
    reservation = Reservation.objects.get(id=reservation_id)
    print(reservation)
    context = {'reservation': reservation}
    return render(request, 'booking/success.html', context)



def room_canceled(request, reservation_id):
    reservation = get_object_or_404(Reservation, id=reservation_id)
    reservation.delete()
    return redirect('HOTEL:cancel-success')




def cancel_success(request):
    return render(request, 'booking/room_canceled.html')   


def payment(request):
    if request.method == "POST":
        name = request.POST.get('name')
        amount = 50000

        client = razorpay.Client(
            auth=("rzp_test_N94crIsOHAqIqA", "mO0T0vP3J6wajyEV6UDDztoG"))

        payment = client.order.create({'amount': amount, 'currency': 'INR',
                                       'payment_capture': '1'})
    return render(request, 'booking/payment.html')

@csrf_exempt
def success(request):
    return render(request, "booking/success.html")


@csrf_exempt
def success(request, reservation_id):
    reservation = Reservation.objects.all(id=reservation_id)
    context = {'reservation': reservation}
    return render(request, 'booking/success.html', context)


@login_required
def dashboard(request):
    user = request.user
    
    if user.is_staff:
        # User is a manager - show all reservations
        reservations = Reservation.objects.all()
        tables = TableReservation.objects.all
        guests = Guest.objects.all()
    else:
        # User is a guest - show only their own reservations
        reservations = Reservation.objects.filter(guest__user=user)
        tables = TableReservation.objects.filter(user=user)
        guests = Guest.objects.filter(reservation__guest__user=request.user)

    
    return render(request, 'booking/dashboard.html', {
        'user': user,
        'reservations': reservations,
        'tables': tables, 
        'guests': guests
        })



# authentications
@csrf_exempt
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('HOTEL:profile')
    else:
        form = UserCreationForm()
    return render(request, 'authentication/signup.html', {
        'form': form
    })


def custom_logout(request):
    logout(request)
    return redirect('HOTEL:index')

@login_required
def profile(request):
    user = request.user
    context = {
        'user': user
    }
    return render(request, 'authentication/profile.html', context)



@login_required
def table_reservation(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        reserve_date = request.POST['reserve_date']
        start_time = request.POST['start_time']
        end_time = request.POST['end_time']
        guest = request.POST['guest']
        table_number = request.POST['table_number']

        # Check if table is available for reservation
        reservations = TableReservation.objects.filter(
            table_number=table_number,
            reserve_date=reserve_date,
            start_time__lte=end_time,
            end_time__gte=start_time,
        )

        if reservations.exists():
            messages.error(request, 'This table is not available for the selected date and time. Please choose another table or time.')
            return redirect('HOTEL:table-reservation')

        # Create a new reservation
        user = request.user
        reservation = TableReservation(
            user=user,
            first_name=first_name,
            last_name=last_name,
            reserve_date=reserve_date,
            start_time=start_time,
            guest=guest,
            end_time=end_time,

            table_number=table_number,
        )
        reservation.save()
        return redirect('HOTEL:reservation-confirmation')

    else:
        tables = TableReservation.TABLE_NUMBER_CHOICES
        context = {
            'table_choices': tables
        }
        return render(request, 'table/reservation.html', context)


    
def table_confirm(request):
    table = TableReservation.objects.filter(user=request.user).latest('id')
    
    table_number = table.table_number
    time = table.start_time
    return render(request, 'table/reservation_confimation.html', {
        'table_number': table_number,
        'time': time
    })

def cancel_table(request, tablereservation_id):
    table = get_object_or_404(TableReservation, id=tablereservation_id)
    table.delete()
    return redirect('HOTEL:cancel-success')


# contact page
@login_required
def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.send_email()
            return render(request, 'authentication/email_sent.html')
    else:
        form = ContactForm()

    context = {
        'form': form,
        'recipient_email': 'fakeavangchhia@.com', # replace with your email address
    }
    return render(request, 'hotel/contact.html', context)

HOTEL/templates/booking/add_room.html
{% extends 'hotel/base.html' %}

{% load%}
{% block content %}
<br><br><br><br><br><br>
  <div class="card container col-md-5">
    <h1 class="text-center display-4 mb-0" style="font-family: 'Respection', cursive;">Add More Room</h1><hr>
    <form method="POST" enctype="multipart/form-data" class="form">
      {% csrf_token %}
      <div class="form-group">
        <label for="room_number">Room number:</label>
        <input type="text" name="room_number" required class="form-control">
      </div>
      <div class="form-group">
        <label for="room_type">Room type:</label>
        <input type="text" name="room_type" required class="form-control">
      </div>
      <div class="form-group">
        <label for="room_description">Room description:</label>
        <textarea name="room_description" rows="4" cols="50" required class="form-control"></textarea>
      </div>
      <div class="form-group">
        <label for="price">Price:</label>
        <input type="number" name="price" step="0.01" required class="form-control">
      </div>
      <div class="form-group">
        <label for="image">Room image:</label>
        <input type="file" name="image" accept="image/*" required class="form-control-file">
      </div>
      <input type="hidden" name="is_booked" value="False">
      <button type="submit" class="btn btn-primary">Add room</button>
    </form>
  </div>
<br><br>
  <style>
    form {
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
      background-color: #f7f7f7;
      border-radius: 5px;
    }

    .form-group {
      margin-bottom: 20px;
    }

    label {
      display: block;
      font-weight: bold;
      margin-bottom: 5px;
    }

    input[type="text"],
    input[type="number"],
    textarea {
      width: 100%;
      padding: 10px;
      border-radius: 5px;
      border: none;
      box-shadow: 0 0 5px #ddd;
    }

    input[type="file"] {
      display: block;
      margin-top: 10px;
    }

    .btn {
      padding: 10px 20px;
      border-radius: 5px;
      border: none;
      background-color: #4CAF50;
      color: #fff;
      font-weight: bold;
      cursor: pointer;
    }

    .btn:hover {
      background-color: #3e8e41;
    }

    .btn:active {
      background-color: #357835;
    }

    .form-control-file {
      padding: 0;
      font-size: inherit;
    }
  </style>
{% endblock %}

HOTEL/templates/booking/dashboard.html
{% extends 'hotel/base.html' %}

{% block content %}
{% block title %}Dashboard{% endblock %}

<br>
<br>
<br>
<br>

<div class="container reservation-container">
  <h1 class="reservation-title">Welcome, {{ user }}!</h1>
  <h2 class="reservation-subtitle">Room Reservations</h2>
  {% if user.is_staff %}
    {% if reservations %}
      <table class="reservation-table">
        <thead>
          <tr>
            <th>Username</th>
            <th>Name</th>
            <th>Room No.</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Price</th>
            <th>Cancel</th>
          </tr>
        </thead>
        <tbody>
          {% for reservation in reservations %}
                <tr>
                  <td>{{ reservation.guest.user }}</td>
                  <td>{{ reservation.guest.first_name }} {{ reservation.guest.last_name }}</td>
                  <td>{{ reservation.room.room_number }}</td>
                  <td>{{ reservation.start_date }}</td>
                  <td>{{ reservation.end_date }}</td>
                  <td>₹{{ reservation.room.price }}</td>
                  <td><a href="{% url 'HOTEL:cancel-reservation' reservation.id %}" class="btn btn-danger">Cancel</a></td>
                </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p class="reservation-message">No customer at the moment.</p>
    {% endif %}
    {% if tables %}
    <p class="reservation-message">Table Reservation.</p>

      <table class="reservation-table">
        <thead>
          <tr>
            <th>Username</th>
            <th>Name</th>
            <th>Table Number</th>
            <th>Reservation Date</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Number of Guest</th>
            <th>Change my plan</th>
          </tr>
        </thead>
        <tbody>
          {% for table in tables %}
                <tr>
                  <td>{{ table.user }}</td>
                  <td>{{ table.first_name }} {{ table.last_name }}</td>
                  <td>{{ table.table_number }}</td>
                  <td>{{ table.reserve_date }}</td>
                  <td>{{ table.start_time }}</td>
                  <th>{{ table.end_time }}</td>
                  <th>{{ table.guest }}</th>
                  <td><a href="{% url 'HOTEL:table-cancel' table.id %}" class="btn btn-danger">Cancel</a></td>
                </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p class="reservation-message">No customer at the moment.</p>
    {% endif %}
  {% else %}
    {% if reservations %}
      <table class="reservation-table">
        <thead>
          <tr>

            <th>Room No.</th>
            <th>Description</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Price</th>
            <th>Cancel</th>
          </tr>
        </thead>
        <tbody>
          {% for reservation in reservations %}
            <tr>
              <td>{{ reservation.room.room_number }}</td>
              <td>{{ reservation.room.room_description }}</td>
              <td>{{ reservation.start_date }}</td>
              <td>{{ reservation.end_date }}</td>
              <td>₹{{ reservation.room.price }}</td>
              <td><a href="{% url 'HOTEL:cancel-reservation' reservation.id %}" class="btn btn-danger">Cancel</a></td>
            </tr>
            {% endfor %}
            </tbody>
          </table>
      {% else %}
    <p class="reservation-message">You do not have any room reservations.</p>
  {% endif %}
  {% if tables %}
    <p class="reservation-message">Table Reservations.</p>

      <table class="reservation-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Table Number</th>
            <th>Reservation Date</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Number of Guest</th>
            <th>Change my plan</th>
          </tr>
        </thead>
        <tbody>
          {% for table in tables %}
                <tr>
                  <td>{{ table.first_name }} {{ table.last_name }}</td>
                  <td>{{ table.table_number }}</td>
                  <td>{{ table.reserve_date }}</td>
                  <td>{{ table.start_time }}</td>
                  <td>{{ table.end_time }}</td>
                  <td>{{ table.guest }}</th>
                  <td><a href="{% url 'HOTEL:table-cancel' table.id %}" class="btn btn-danger">Cancel</a></td>
                </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p class="reservation-message">You do not have any table reservations.</p>
    {% endif %}
{% endif %}

</div>
<br>
<br>
<br>

<style>
/* Add some cool CSS styles here */
.reservation-container {
  background-color: #e8eaf6;
  border-radius: 10px;
  box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.2);
  padding: 20px;
  text-align: center;
}

.reservation-title {
  font-size: 3rem;
  font-weight: bold;
  margin-bottom: 10px;
}

.reservation-subtitle {
  font-size: 2rem;
  margin-bottom: 20px;
}

.reservation-table {
  width: 100%;
  border-collapse: collapse;
  margin-top: 20px;
}

.reservation-table th,
.reservation-table td {
  padding: 10px;
  text-align: center;
  border: 1px solid #ccc;
}

.reservation-table th {
  font-weight: bold;
  background-color: #fff;
}

.reservation-table tr:hover {
  background-color: #f5f5f5;
}

.reservation-message {
  font-size: 1.5rem;
  margin-top: 20px;
}
</style>
{% endblock %}

HOTEL/templates/booking/payment.html
<head>
    <style>
        .center {
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
        }
    </style>
</head>

<div class="center">

    <form class="text-center border border-light p-5" action="HOTEL:index" method="POST">
        {% csrf_token %}

        <p class="h3 mb-3"><i class="fas fa-coffee"></i> BUY ME A COFFEE!!</p>
        <p class="mb-3">Help us create more videos by donating 500 INR</p>

        <input type="name" name="name" id="name" required class="form-control mb-4" placeholder="Name">

        <!-- RAZORPAY INTEGRATION HERE -->
        <script src="https://checkout.razorpay.com/v1/checkout.js" 
        data-key="rzp_test_N94crIsOHAqIqA" 
        data-amount="50000"
        data-currency="INR" 
        data-order_id="{{payment.id}}" 
        data-buttontext="Pay with Razorpay"
        data-name="Professional Cipher"
        data-description="Django and Data Science"
        data-image="https://example.com/your_logo.jpg" 
        data-prefill.name="PC"
        data-prefill.email="pc@studygyaan.com" 
        data-theme.color="#F37254"></script>

    </form>

</div>


</div>

HOTEL/templates/booking/payment_success.html
{% block content %}

<head>
    <style>
        .center {
            position: absolute;
            text-align: center;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
        }
    </style>
</head>

<body>
    <div class="center">
        <h3>
            Thanks, You are aweseome! <i class="fas fa-check-circle"></i>
        </h3>
        <h5>
            <a href="http://127.0.0.1:8000/">
                Again?
            </a>
        </h5>
    </div> 
</body>

{% endblock content %}

HOTEL/templates/booking/reservation_cancel.html
{% extends 'hotel/base.html' %}

{% block content %}
{% block title  %} Cancellation Successful {% endblock %}
<link rel="stylesheet" href="path/to/icon-font.css">

<br><br><br>
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card border-0 shadow-lg">
        <div class="card-body text-center">
          <i class="fas fa-check-circle fa-5x text-success"></i>
          <h1 class="mt-4 mb-3">Cancellation Successful</h1>
          <p class="lead">Your reservation has been cancelled.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
{% endblock %}

{% block scripts %}
<script>
  $(".card").addClass("animate__animated animate__bounceIn");
</script>
{% endblock %}

HOTEL/templates/booking/reserve_room.html
{% extends 'hotel/base.html' %}

{% block content %}
{% block title  %} Book Room {% endblock %}

<br>
<br>
<br>
<br>
<br>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 col-lg-6">
      <div class="card">
        <div class="card-header bg-success text-white text-center">
          <h3 class="m-0">Reservation Details</h3>
        </div>
        <div class="card-body">
          <form method='POST'>
            {% csrf_token %}
            <input type="hidden" name="room_number" value="{{ room_number }}">
            <div class="form-group">
              <label for="first_name">First Name:</label>
              <input type="text" id="first_name" name="first_name" class="form-control" required>
            </div>
            <div class="form-group">
              <label for="last_name">Last Name:</label>
              <input type="text" id="last_name" name="last_name" class="form-control" required>
            </div>
            <div class="form-group">
              <label for="email">Email:</label>
              <input type="email" id="email" name="email" class="form-control" required>
            </div>
            <div class="form-group">
              <label for="phone_number">Phone Number:</label>
              <input type="text" id="phone_number" name="phone_number" class="form-control" required>
            </div>
            <div class="form-group">
              <label for="start_date">Check In:</label>
              <input type="date" id="start_date" name="start_date" class="form-control" required>
            </div>
            <div class="form-group">
              <label for="end_date">Check Out:</label>
              <input type="date" id="end_date" name="end_date" class="form-control" required>
            </div>
            <!-- Add this hidden input field for payment -->
            
            <input type="hidden" name="room_payment" value="paid">
            <input type="submit" class="btn btn-primary" value="Reserve Room">
          </form>
          
        </div>
      </div>
    </div>
  </div>
</div>
<br>
{% endblock %}

HOTEL/templates/booking/room_search.html
{% extends 'hotel/base.html' %}

{% block content %}
{% block title  %} Search Room {% endblock %}

<div class='container' style='padding-top: 150px' >
  <div class="room-search-form">
    <h2>Find Your Perfect Room</h2>
    <form method="GET" action="{% url 'HOTEL:search-room' %}">
      <div class="form-group">
        <label for="start-date">Check-in Date:</label>
        <input type="date" class="form-control" name="start_date" id="start-date" value="{{ start_date }}" required>
      </div>
      <div class="form-group">
        <label for="end-date">Check-out Date:</label>
        <input type="date" class="form-control" name="end_date" id="end-date" value="{{ end_date }}" required>
      </div>
      <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> Search Rooms</button>
    </form>
  </div>
  <br><br>
  <!-- Room Start -->
  {% if start_date and end_date %}
    {% if available_rooms_list %}
    <div class="container-xxl py-5">
      <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
          <h6 class="section-title text-center text-primary text-uppercase">Our Rooms</h6>
          <h1 class="mb-5">Explore Our <span class="text-primary text-uppercase">Rooms</span></h1>
        </div>
        <div class="row g-4 flex-row-reverse">
          {% for room in available_rooms_list %}
            <div class="col-lg-4 col-md-6 mb-4 wow fadeInUp" data-wow-delay="0.1s">
              <div class="room-item shadow rounded overflow-hidden">
                <div class="position-relative">
                  <img class="img-fluid" src="{{ room.image }}" alt="">
                </div>
                <div class="p-4 mt-2">
                  <div class="d-flex justify-content-between mb-3">
                    <h5 class="mb-0">{{ room.room_number }}</h5>
                    <div class="ps-2">
                      <small class="fa fa-star text-primary"></small>
                      <small class="fa fa-star text-primary"></small>
                      <small class="fa fa-star text-primary"></small>
                      <small class="fa fa-star text-primary"></small>
                      <small class="fa fa-star text-primary"></small>
                    </div>
                    <small class="position-absolute start-0 top-100 translate-middle-y bg-primary text-white rounded py-1 px-3 ms-4">₹{{ room.price }}</small>
                  </div>
                  <div class="d-flex mb-3">
                    <small class="border-end me-3 pe-3"><i class="fa fa-bed text-primary me-2"></i>{{ room.room_type }} </small>                              
                    <small><i class="fa fa-wifi text-primary me-2"></i>Wifi</small>
                  </div>
                  <p class="text-body mb-3">{{ room.room_description }}</p>
                  <div class="d-flex justify-content-between">
                    <a class="btn btn-sm btn-primary rounded py-2 px-4" href="#">Room no.{{ room.room_number }}</a>
                      <a class="btn btn-sm btn-dark rounded py-2 px-4" href="{% url 'HOTEL:reserve-room' room.room_number %}">Book Now</a>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
          <br>
        </div>
      </div>
    </div>
    </div>
  </div>
{% else %}
  <h4>No rooms available for the selected dates.</h4>
{% endif %}
{% endif %}
</div>
<!-- Room End -->
{% endblock %}

HOTEL/templates/booking/success.html
{% extends 'hotel/base.html' %}

{% load static %}
{% block content %}
    <br><br>
    <br><br>
    <br><br>
    <div class="container">
        <div class="success-message">
          <h3>Room Booking Success: {{ reservation.id }}</h3>
          <h3>Room Booking Success: {{ reservation.guest }}</h3>
          <h3>Room Booking Success: {{ reservation.room }}</h3>
          <button class="btn btn-outline-warning" onclick="location.href='{% url 'HOTEL:dashboard' %}'">Goto Dashboard</button>
        </div>
      </div>

    <br><br>
    <br><br>
    <br><br>
      
      <style>
        .container {
          text-align: center;
        }
        
        .success-message {
          background-color: #f7f7f7;
          padding: 20px;
          border-radius: 5px;
          box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
        }
        
        .success-message h3 {
          color: #42b983;
          font-size: 24px;
          margin-bottom: 10px;
        }
        </style>
{% endblock %}